import Navbar from './Navbar';
import Footer from './Footer';
import Head from 'next/head';

const Layout = ({children}) => {
  return (
    <>
    <Head>
      <title>Avachar</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" integrity="sha512-wnea99uKIC3TJF7v4eKk4Y+lMz2Mklv18+r4na2Gn1abDRPPOeef95xTzdwGD9e6zXJBteMIhZ1+68QC5byJZw==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
    </Head>
    <div className="content bg-gray-100">
      <Navbar/>
      {children}
      <Footer/>
    </div>
    </>
   );
}
 
export default Layout;